---
title: "Databases with R"
author: "Kevin Stierhoff"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Most of the code here was adapted from the [Databases Using R](https://db.rstudio.com/) site from Rstudio.

# Install and load required packages.  

```{r Setup, message=F,error=F,warning=F}
# Install and load pacman (library management package)
if (!require("pacman")) install.packages("pacman")

# Install and load required packages from CRAN ---------------------------------
pacman::p_load(RODBC,DBI,dbplot,dbplyr,dplyr,ggplot2,knitr,RMySQL,
               odbc,parallelMap,R.utils,readr,tidypredict)
```

```{r}
# Define a connection to the Training database located in the Data dir
con <- dbConnect(odbc::odbc(), "training", timeout = 10)

# Create a pointer to the cruise table in the database 
cruise <- tbl(con, "dbo_CRUISE")

cruise
```

```{r}
cruise.c <- tbl(con, "dbo_CRUISE") %>% collect()

cruise.c
```


```{r}
# This is a lazy query that doesn't actually touch the database
# It is a LIST object, with info about the database
leader.summ <- cruise %>% 
  group_by(LEADER) %>% 
  summarise(n_cruises = n())

# It is a LIST object, with info about the database
leader.tally <- cruise %>% 
  group_by(LEADER) %>% 
  tally()

leader.count <- cruise.c %>% 
  add_count(LEADER) %>% 
  filter(n == 1)
```


```{r}
# It's not until you use the collect() function that the data are returned to an object (a tibble in this case)
leader.summ.c <- cruise %>% 
  group_by(LEADER) %>% 
  summarise(n_cruises = n()) %>% 
  collect()
```

```{r}
con.rov <- dbConnect(odbc::odbc(), "ROV2", timeout = 10)

nav <- tbl(con.rov, "tbl_NAV")

# nav.c <- tbl(con.rov, "tbl_NAV") %>% collect()

# nav.sub <- tbl(con.rov, "tbl_NAV") %>% 
#   select(nav_id:date_time,lat = lat_r, long = long_r) %>% 
#   filter(dive_name == "02-158A") %>% 
#   collect()

nav.sub <- tbl(con.rov, "tbl_NAV") %>% 
  select(nav_id:date_time,lat = lat_r, long = long_r) %>% 
  filter(dive_name == "02-158A") %>% 
  ggplot() + geom_path(aes(long,lat))

dbDisconnect(con.rov)

nav.sub + coord_map() + theme_bw()
```



